replicaCount: 1

image:
  repository: 656732674839.dkr.ecr.eu-north-1.amazonaws.com/goals-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 32000

ingress:
  enabled: false
