apiVersion: apps/v1
kind: Deployment
metadata:
  name: goals-app
  labels:
    app: goals-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: goals-app
  template:
    metadata:
      labels:
        app: goals-app
    spec:
      containers:
      - name: goals-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"